//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Odontograma
    {
        public int SQC_Odon { get; set; }
        public string Odo_Observacao { get; set; }
    }
}
