//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Paciente
    {
        public int SQC_Paciente { get; set; }
        public string Pac_Nome { get; set; }
        public string Pac_Rg { get; set; }
        public string Pac_Endereco { get; set; }
        public Nullable<System.DateTime> Pac_DataNascimento { get; set; }
        public string Pac_Telefone { get; set; }
        public string Pac_Responsavel { get; set; }
        public string Pac_MotivoConsulta { get; set; }
        public string Pac_EstadoCivil { get; set; }
        public string Pac_Cpf { get; set; }
    }
}
