//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Periograma
    {
        public int SQC_Peri { get; set; }
        public string Per_Diagnostico { get; set; }
        public string Per_Prognostico { get; set; }
        public Nullable<double> Per_IndiceBiofilme { get; set; }
        public Nullable<double> Per_IindiceSangramento { get; set; }
    }
}
