//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Pessoa()
        {
            this.TB_Triagem = new HashSet<TB_Triagem>();
        }
    
        public int SQC_Pessoa { get; set; }
        public int Pes_Rg { get; set; }
        public string Pes_Cpf { get; set; }
        public string Pes_Nome { get; set; }
        public string Pes_Telefone { get; set; }
        public string Pes_Endereco { get; set; }
        public System.DateTime Pes_DataNascimento { get; set; }
        public string Pes_Cidade { get; set; }
        public string Pes_Bairro { get; set; }
        public string Pes_Numero { get; set; }
        public string Pes_Cep { get; set; }
        public string Pes_Email { get; set; }
        public string Pes_Senha { get; set; }
        public string Pes_Matricula { get; set; }
        public int Pes_TipoUsuario { get; set; }
        public string Pes_NomeMae { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Triagem> TB_Triagem { get; set; }
    }
}
