//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Perguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Perguntas()
        {
            this.TB_Perguntas1 = new HashSet<TB_Perguntas>();
        }
    
        public int SQC_Pergunta { get; set; }
        public int TB_Perguntas_SQC_Pergunta { get; set; }
        public string Pgt_Enunciado { get; set; }
        public string Pgt_Conclusao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Perguntas> TB_Perguntas1 { get; set; }
        public virtual TB_Perguntas TB_Perguntas2 { get; set; }
    }
}
