//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Triagem
    {
        public int SQC_Triagem { get; set; }
        public int TB_Pessoa_SQC_Pessoa { get; set; }
        public int TB_Paciente_SQC_Paciente { get; set; }
        public Nullable<bool> Tri_Radiologia { get; set; }
        public Nullable<bool> Tri_Periapical { get; set; }
        public Nullable<bool> Tri_Panoramica { get; set; }
        public Nullable<bool> Tri_Interproximal { get; set; }
        public Nullable<bool> Tri_Dentistica { get; set; }
        public Nullable<bool> Tri_ClasseI { get; set; }
        public Nullable<bool> Tri_ClasseII { get; set; }
        public Nullable<bool> Tri_ClasseIII { get; set; }
        public Nullable<bool> Tri_ClasseIV { get; set; }
        public Nullable<bool> Tri_ClasseV { get; set; }
        public Nullable<bool> Tri_Clareamento { get; set; }
        public Nullable<bool> Tri_Periodontia { get; set; }
        public Nullable<bool> Tri_Cirurgia { get; set; }
        public Nullable<bool> Tri_Simples { get; set; }
        public Nullable<bool> Tri_Avancado { get; set; }
        public Nullable<bool> Tri_Endodontia { get; set; }
        public Nullable<bool> Tri_Pediatria { get; set; }
        public Nullable<bool> Tri_Protese { get; set; }
        public Nullable<bool> Tri_ProtesePt { get; set; }
        public Nullable<bool> Tri_ProtesePpr { get; set; }
        public Nullable<bool> Tri_ProteseFixa { get; set; }
        public Nullable<bool> Tri_CicloII { get; set; }
        public string Tri_Descricao { get; set; }
        public Nullable<System.DateTime> Tri_DataRealizacao { get; set; }
        public Nullable<bool> Tri_CicloIII { get; set; }
        public Nullable<bool> Tri_CicloIV { get; set; }
        public Nullable<bool> Tri_CicloV { get; set; }
        public string Tri_MotivoConsulta { get; set; }
        public Nullable<bool> Tri_Procedimento { get; set; }
    
        public virtual TB_Paciente TB_Paciente { get; set; }
        public virtual TB_Pessoa TB_Pessoa { get; set; }
    }
}
