//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem_PT_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem_PT_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mensagem_PT_BR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a CPF existente.
        /// </summary>
        internal static string CpfExistente {
            get {
                return ResourceManager.GetString("CpfExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O CPF é obrigatório.
        /// </summary>
        internal static string CpfRequerido {
            get {
                return ResourceManager.GetString("CpfRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O email é obrigatório.
        /// </summary>
        internal static string EmailRequerido {
            get {
                return ResourceManager.GetString("EmailRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Login Existente.
        /// </summary>
        internal static string LoginExistente {
            get {
                return ResourceManager.GetString("LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O Login é obrigatório.
        /// </summary>
        internal static string LoginRequerido {
            get {
                return ResourceManager.GetString("LoginRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O login deve possuir entre 5 a 20 caracteres.
        /// </summary>
        internal static string LoginTamanhoInvalido {
            get {
                return ResourceManager.GetString("LoginTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Matrícula Existente.
        /// </summary>
        internal static string MatriculaExistente {
            get {
                return ResourceManager.GetString("MatriculaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A Matrícula é obrigatória.
        /// </summary>
        internal static string MatriculaRequerida {
            get {
                return ResourceManager.GetString("MatriculaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Motivo da consulta é obrigatório.
        /// </summary>
        internal static string MotivoConsultaRequerido {
            get {
                return ResourceManager.GetString("MotivoConsultaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O nome completo é obrigatório.
        /// </summary>
        internal static string NomeRequerido {
            get {
                return ResourceManager.GetString("NomeRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O nome deve possuir entre 2 a 300 caracteres.
        /// </summary>
        internal static string NomeTamanhoInvalido {
            get {
                return ResourceManager.GetString("NomeTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Rg existente.
        /// </summary>
        internal static string RgExistente {
            get {
                return ResourceManager.GetString("RgExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O RG é obrigatório.
        /// </summary>
        internal static string RgRequerido {
            get {
                return ResourceManager.GetString("RgRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Senha inválida. Utilize caracteres alfabéticos maiúsculos e minúsculos, números, underscore ( _ ) e hífen ( - ).
        /// </summary>
        internal static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A senha é obrigatória.
        /// </summary>
        internal static string SenhaRequerida {
            get {
                return ResourceManager.GetString("SenhaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A senha e sua confirmação não são correspondentes.
        /// </summary>
        internal static string SenhasDiferentes {
            get {
                return ResourceManager.GetString("SenhasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A senha deve possuir entre 8 a 100 caracteres.
        /// </summary>
        internal static string SenhaTamanhoInvalido {
            get {
                return ResourceManager.GetString("SenhaTamanhoInvalido", resourceCulture);
            }
        }
    }
}
